// <auto-generated />
using System;
using EmployeeManagement.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeManagement.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230524201554_updateModels")]
    partial class updateModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("EmployeeManagement.Models.Company", b =>
                {
                    b.Property<string>("CNPJ")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TradeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CNPJ");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("EmployeeManagement.Models.Employee", b =>
                {
                    b.Property<string>("RegisterNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyCNPJ")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RegisterNumber");

                    b.HasIndex("CompanyCNPJ");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("EmployeeManagement.Models.JobTitle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActivityDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CBO")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeRegisterNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TerminationDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeRegisterNumber");

                    b.ToTable("JobTitles");
                });

            modelBuilder.Entity("EmployeeManagement.Models.Employee", b =>
                {
                    b.HasOne("EmployeeManagement.Models.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyCNPJ");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("EmployeeManagement.Models.JobTitle", b =>
                {
                    b.HasOne("EmployeeManagement.Models.Employee", "Employee")
                        .WithMany("JobHistory")
                        .HasForeignKey("EmployeeRegisterNumber");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EmployeeManagement.Models.Company", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("EmployeeManagement.Models.Employee", b =>
                {
                    b.Navigation("JobHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
